export const DEFAULT_ROLES = {
  ADMIN: "admin",
  USER: "user",
};

export const ROLES = {
  SURGERY: "surgery",
  OPERATING: "operating",
  ANESTHESIOLOGY: "anesthesiology",
  HEAD_DOCTOR: "head_doctor",
  ACCOUNTING: "accounting",
  PHARMACY: "pharmacy",
  RESUSCITATION: "resuscitation",
};

export const ACCESS_RULES = {
  REPORTS: [
    DEFAULT_ROLES.ADMIN,
    DEFAULT_ROLES.USER,
    ROLES.ACCOUNTING,
    ROLES.PHARMACY,
    ROLES.SURGERY,
    ROLES.OPERATING,
    ROLES.ANESTHESIOLOGY,
    ROLES.RESUSCITATION,
  ],
  STATISTICS: [DEFAULT_ROLES.ADMIN, DEFAULT_ROLES.USER, ROLES.HEAD_DOCTOR],
  USERS: [],
  MAIN_PAGE: [],
  CREATE_NEWS: [],
};

export const DEFAULT_ACCESS_RULES = {
  USERS: [DEFAULT_ROLES.ADMIN],
  CREATE_NEWS: [DEFAULT_ROLES.ADMIN, DEFAULT_ROLES.USER, ROLES.HEAD_DOCTOR],
};
